# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.WORKFLOW_DATABASE_TEST }}
          MYSQL_DATABASE: dev
          MYSQL_USER: testUser
          MYSQL_PASSWORD: ${{ secrets.WORKFLOW_DATABASE_TEST }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build and Test with Maven
        run: mvn clean install
        env:
          DB_USERNAME: testUser
          DB_PASSWORD: ${{ secrets.WORKFLOW_DATABASE_TEST }}
          DB_HOST: localhost
          DB_PORT: 3306
          DB_NAME: dev

      - name: Set unique image tag
        id: unique-image-tag
        run: echo "IMAGE_TAG=dev-${{ github.sha }}" >> $GITHUB_ENV

      - name: Build & push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: danielneset/idata2306dev:${{ env.IMAGE_TAG }}
